#!/bin/bash

source venv/bin/activate
export microsoft_client_id=9886b2e7-684b-4370-b515-f54accde5490
export PYTHONUNBUFFERED=1
export microsoft_secret=ZbG2MvqJqy33zq3j3qPUQ7c
export pubnub_subscribe_key=sub-c-6cbc7d16-f09c-11e6-9283-02ee2ddab7fe
export pubnub_publish_key=pub-c-0644c683-0882-4d28-b6ac-81acf63ba847
export DEVELOPMENT=TRUE
python application.py
